resolver: lts-12.16
packages:
- .
nix:
  packages:
    - zlib.dev
    - zlib.out
ghc-options:
  "wai-gateway": -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
