resolver: lts-11.9
packages:
- .
extra-deps:
- serverless-haskell-0.6.1
- amazonka-core-1.6.0
- amazonka-kinesis-1.6.0
- amazonka-s3-1.6.0
nix:
  packages:
    - zlib.dev
    - zlib.out
ghc-options:
  "wai-gateway": -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
